### ISSUE TITLE
Plan to release to CRAN?

### ISSUE THREAD

**Issue by brodieG** [hrbrmstr/hyphenatr#1]
Looking to implement some text wrapping code that hyphenates properly (instead of the horrible kludge I'm using now).  Are you planning on releasing to CRAN?  Thanks for making this code available publicly.

**Comment by hrbrmstr** [comment]
https://cran.rstudio.com/web/packages/hyphenatr/

**Comment by brodieG** [comment]
I'm sorry, I should have checked.  Just assumed based on readme that it wasn't.

**Comment by hrbrmstr** [comment]
np (was in a hurry before hence just the link). I'll get some of the badges
up this week.
